### PR TITLE
Update link to Project Principles in README

### PR DESCRIPTION
**Pull request by garyboyle**

### CODE REVIEW

**Comment by NickColley** [comment]
Thanks Gary, appreciate it. 👍

**Comment by NickColley** [comment]
If you have time, could you update the https://github.com/alphagov/govuk-prototype-kit-private-beta/blob/master/CHANGELOG.md file, so when we do a release users know what has changed.

If not I can do this for you :)

**Comment by garyboyle** [comment]
Sure @nickcolley.  I've just done it.

**Comment by NickColley** [comment]
We're currently moving everything from this repository into the main repo, so I'll bring these changes over.

Thanks again :)

**Pull request closed without merging**
